CREATE TABLE [dbo].['2020$'] (
    [Country]                          NVARCHAR (255) NULL,
    [Year]                             DATETIME       NULL,
    [Rank]                             NVARCHAR (255) NULL,
    [Total]                            FLOAT (53)     NULL,
    [C1: Security Apparatus]           FLOAT (53)     NULL,
    [C2: Factionalized Elites]         FLOAT (53)     NULL,
    [C3: Group Grievance]              FLOAT (53)     NULL,
    [E1: Economy]                      FLOAT (53)     NULL,
    [E2: Economic Inequality]          FLOAT (53)     NULL,
    [E3: Human Flight and Brain Drain] FLOAT (53)     NULL,
    [P1: State Legitimacy]             FLOAT (53)     NULL,
    [P2: Public Services]              FLOAT (53)     NULL,
    [P3: Human Rights]                 FLOAT (53)     NULL,
    [S1: Demographic Pressures]        FLOAT (53)     NULL,
    [S2: Refugees and IDPs]            FLOAT (53)     NULL,
    [X1: External Intervention]        FLOAT (53)     NULL,
    [Change from Previous Year]        FLOAT (53)     NULL,
    [F18]                              NVARCHAR (255) NULL,
    [F19]                              NVARCHAR (255) NULL,
    [F20]                              NVARCHAR (255) NULL,
    [F21]                              NVARCHAR (255) NULL,
    [F22]                              NVARCHAR (255) NULL,
    [F23]                              NVARCHAR (255) NULL,
    [F24]                              NVARCHAR (255) NULL,
    [F25]                              NVARCHAR (255) NULL,
    [F26]                              NVARCHAR (255) NULL,
    [F27]                              NVARCHAR (255) NULL,
    [F28]                              NVARCHAR (255) NULL,
    [F29]                              NVARCHAR (255) NULL,
    [F30]                              NVARCHAR (255) NULL,
    [F31]                              NVARCHAR (255) NULL,
    [F32]                              NVARCHAR (255) NULL,
    [F33]                              NVARCHAR (255) NULL,
    [F34]                              NVARCHAR (255) NULL,
    [F35]                              NVARCHAR (255) NULL,
    [F36]                              NVARCHAR (255) NULL,
    [F37]                              NVARCHAR (255) NULL,
    [F38]                              NVARCHAR (255) NULL,
    [F39]                              NVARCHAR (255) NULL
);

